### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by lukemelas** [gsssrao/youtube-8m-videos-frames#9]
When I download more than around 20 videos, I receive 
```
[youtube] AjXREq9YqUQ: Downloading webpage ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests
```
Is this a known issue -- is there any way to fix it and download the videos? 

I'm only looking for the videos in four categories (Solo dance, Ballroom dance, Ballet Dancer, and Dance studio).

**Comment by gsssrao** [comment]
I tried to see if I could replicate the issue you mentioned by downloading like ~45 vids and I am able to download them with no issues. 

So, currently [youtube-dl](https://github.com/ytdl-org/youtube-dl) is being used for downloading the youtube videos. The error you mentioned `HTTP Error 429: Too Many Requests` is raised by youtube-dl. I tried looking up the error and there seem to some relevant youtube-dl issues: [#22839](https://github.com/ytdl-org/youtube-dl/issues/22839), [#21729](https://github.com/ytdl-org/youtube-dl/issues/21729), [#21700](https://github.com/ytdl-org/youtube-dl/issues/21700) etc. 

If you look up the [youtube-dl faq](https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required), it mentions that the error code 429 is caused when your ip has been blacklisted. Some of the solutions posted in the issue include:

- Adding a delay before each download
- Using a proxy 
- Using different machine (like home machine, university/office machine, laptop, friend's machine etc)

I think that probably your ip has been blocked, maybe try accessing youtube.com from your machine and you should probably get a captcha or unusual traffic post or something similar. I would recommend checking out some of the solutions posted in those issues. 

If you want to add a delay or modify the youtube-dl command, you can edit lines [31](https://github.com/gsssrao/youtube-8m-videos-frames/blob/master/downloadvideos.sh#L31) and [40](https://github.com/gsssrao/youtube-8m-videos-frames/blob/master/downloadvideos.sh#L40) in `downloadvideos.sh` or add something like `sleep 5` before them.

If you can propose some other way for me to replicate the issue, I can look into it more. But otherwise, I am sorry, I can't offer a fix without being able to replicate the issue.

**Comment by lukemelas** [comment]
Hello, 

Thank you for the long and comprehensive response. I very much appreciate you taking the time to respond to my issue. 

I also found that the problem was youtube-dl. I have tried using servers on Microsoft Azure, Google Cloud, and AWS. All get blocked after downloading around 50 videos. 

Out of interest, have you tried downloading a large number of videos recently? If so, what computer/server are you using? 

Thanks again! 
Luke

**Comment by gsssrao** [comment]
So, I tried downloading 70-100 videos on couple of machines and it seems to work well on my end. The machines I used were:

- Macbook Pro
- 2 Ubuntu Servers at 2 different locations (hence different IPs)

The servers aren't cloud servers, they are on-premise machines. Since you are using cloud servers, those ips might have been blocked or blacklisted. Maybe try using a delay or a proxy like socks5 and see if that works. Or else a workaround might be to download on local machines like your laptop or desktop and then pushing it to servers.

**Comment by lukemelas** [comment]
Thanks, I'll try and get back to you!

**Comment by lukemelas** [comment]
I used a different (non-server) computer and everything worked. Thank you for your brilliant work!

**Comment by lukemelas** [comment]
I will close this issue for now and re-open it if I experience this issue again in the future.
